### ISSUE TITLE
Test UIScrollView isAtTheBottom with massive scroll views

### ISSUE THREAD

**Issue by 3lvis** [bakkenbaeck/SweetUIKit#34]

**Comment by 3lvis** [comment]
> The reason I ask is because AFAIK scrollviews (since iOS7, at least) have been absurdly unreliable at giving you accurate content sizes after a certain size threshold.

— @Elland

**Comment by 3lvis** [comment]
I've used this in an app with around 80k elements and it worked.

**Comment by elland** [comment]
Good to know. 👍 Which iOS version tho?

**Comment by 3lvis** [comment]
@Elland iOS 9 and iOS 10.

**Comment by elland** [comment]
@3lvis brilliant. ✨

**Comment by 3lvis** [comment]
Might be a lot of work to test this, I tested that it worked in other app, let's reopen if this becomes an issue in the future or someone else reports this.
